name: deploy on CloudFunctions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job_id:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Create file from variables"
        run: echo "${{ vars.URL_LIST }}" > feeds.txt

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Use to deploy a cloud function gen 2"
        run: "gcloud functions deploy feed-summarizer \
          --gen2 \
          --runtime=go120 \
          --region=asia-northeast1 \
          --source=. \
          --entry-point=SummarizeFeed \
          --set-env-vars ${{ secrets.CLOUD_FUNCTIONS_ENV_VARS }} \
          --trigger-http "
